spring.application.name=ViajeSeguroSpringBoot

#CONFIGURACION A LA BASE DE DATOS MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/bd_ViajeSeguro
spring.datasource.username=root
spring.datasource.password=
#determinar el driver MYSQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#algunas configuraciones importantes
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

      




